version: '2'
services:


  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
      - /var/log/transcriptor/:/var/log/transcriptor/
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: elasticsearch:6.6.2
    environment:
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
    expose:
      - 9200
    ports:
      - "9200:9200"
    

  kibana:
    image: kibana:6.6.2
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"
